<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=tools
 * [END_COT_EXT]
 */
 
/**
 * plugin GeoPage for Cotonti Siena
 * 
 * @package geopage
 * @version 2.0.0
 * @author esclkm
 * @copyright (c) esclkm 2008-2011
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_langfile('geopage', 'plug');

require_once cot_incfile('forms');
require_once cot_incfile('extrafields');
require_once cot_incfile('page', 'module');
$geo_t = new XTemplate(cot_tplfile('geopage.admin', 'plug'));

if ($a == 'update' && !empty($_POST['rpage_geo_country']))
{
	$rpage_geo_country = cot_import('rpage_geo_country', 'P', 'ARR');
	$rpage_geo_region = cot_import('rpage_geo_region', 'P', 'ARR');
	$rpage_geo_locality = cot_import('rpage_geo_locality', 'P', 'ARR');
	$rpage_geo_street = cot_import('rpage_geo_street', 'P', 'ARR');
	$rpage_geo_latitude = cot_import('rpage_geo_latitude', 'P', 'ARR');
	$rpage_geo_longitude = cot_import('rpage_geo_longitude', 'P', 'ARR');
	
	foreach ($rpage_geo_country as $key => $val)
	{
		$rx['page_geo_country'] = cot_import($rpage_geo_country[$key], 'D', 'TXT');
		$rx['page_geo_region'] = cot_import($rpage_geo_region[$key], 'D', 'TXT');
		$rx['page_geo_locality'] = cot_import($rpage_geo_locality[$key], 'D', 'TXT');
		$rx['page_geo_street'] = cot_import($rpage_geo_street[$key], 'D', 'TXT');
		$rx['page_geo_latitude'] = cot_import($rpage_geo_latitude[$key], 'D', 'TXT');
		$rx['page_geo_longitude'] = cot_import($rpage_geo_longitude[$key], 'D', 'TXT');
		
		$db->update($db_pages, $rx, 'page_id='.(int)$key);
	}
}

switch ($cfg['plugin']['geopage']['key'])
{
	default:
		$mapdriver = 'http://api-maps.yandex.ru/1.1/index.xml?key='.$cfg['plugin']['geopage']['key'];
		break;
}


$GEOJS = '
<script type="text/javascript" src="'.$cfg['plugins_dir'].'/geopage/lib/mxn.js?('.$cfg['plugin']['geopage']['engine'].')"></script>
<script src="'.$mapdriver.'" type="text/javascript"></script>
<script type="text/javascript">
	var map_engine = "'.$cfg['plugin']['geopage']['engine'].'";
	var map_defzoom = "'.$cfg['plugin']['geopage']['defzoom'].'";
	var map_deflat = "'.$cfg['plugin']['geopage']['deflat'].'";
	var map_deflon = "'.$cfg['plugin']['geopage']['deflon'].'";
	var map_pointzoom = "'.$cfg['plugin']['geopage']['pointzoom'].'";
	var map_lat = "'.(float)$pag['page_geo_latitude'].'";
	var map_lon = "'.(float)$pag['page_geo_longitude'].'";
	var map_title = "'.htmlspecialchars($pag['page_title']).'";	
</script>
<script type="text/javascript" src="'.$cfg['plugins_dir'].'/geopage/js/admin.js"></script>';


$sql = $db->query("SELECT * FROM $db_pages WHERE 
	(page_geo_country <> '' AND page_geo_region <> '' AND page_geo_street <> '' AND page_geo_locality <> '') 
	AND (page_geo_latitude = '' AND page_geo_longitude = '') ORDER BY page_date DESC LIMIT 100");
$totalcount = $db->query("SELECT COUNT(*) FROM $db_pages WHERE 
	(page_geo_country <> '' AND page_geo_region <> '' AND page_geo_street <> '' AND page_geo_locality <> '') 
	AND (page_geo_latitude = '' AND page_geo_longitude = '')")->fetchColumn();

$jj = 0;
foreach ($sql->fetchAll() as $pag)
{
	$jj++;
	$geo_t->assign(cot_generate_pagetags($pag, 'PAGE_ROW_'));
	$geo_t->assign(array(
		'PAGE_ROW_GEO_COUNTRY' => cot_inputbox('text', 'rpage_geo_country['.$pag['page_id'].']', $pag['page_geo_country'], 'class="geo_country"'),
		'PAGE_ROW_GEO_REGION' => cot_inputbox('text', 'rpage_geo_region['.$pag['page_id'].']', $pag['page_geo_region'], 'class="geo_region"'),
		'PAGE_ROW_GEO_LOCALITY' => cot_inputbox('text', 'rpage_geo_locality['.$pag['page_id'].']', $pag['page_geo_locality'], 'class="geo_locality"'),
		'PAGE_ROW_GEO_STREET' => cot_inputbox('text', 'rpage_geo_street['.$pag['page_id'].']', $pag['page_geo_street'], 'class="geo_street"'),
		'PAGE_ROW_GEO_LATITUDE' => cot_inputbox('text', 'rpage_geo_latitude['.$pag['page_id'].']', $pag['page_geo_latitude'], 'class="geo_latitude"'),
		'PAGE_ROW_GEO_LONGITUDE' => cot_inputbox('text', 'rpage_geo_longitude['.$pag['page_id'].']', $pag['page_geo_longitude'], 'class="geo_longitude"'),
		'PAGE_ROW_IDCLASS' => 'geoid'.$pag['page_id'],
		'PAGE_ROW_ODDEVEN' => cot_build_oddeven($jj),
		'PAGE_ROW_NUM' => $jj
	));

	$geo_t->parse('MAIN.PAGE_ROW');
}
if($jj == 0)
{
	$geo_t->parse('MAIN.PAGE_NOROW');
}

$geo_t->assign(array(
	'PAGE_GEOJS' => $GEOJS,
	'PAGE_URL' => cot_url('admin', 'm=other&p=geopage&a=update'),
));
$geo_t->parse('MAIN');
$plugin_body = $geo_t->text('MAIN');

?>