<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=page.tags
 * Tags=page.list.tpl:{GEOMAP}
 * [END_COT_EXT]
 */
 
/**
 * plugin GeoPage for Cotonti Siena
 * 
 * @package geopage
 * @version 2.0.0
 * @author esclkm
 * @copyright (c) esclkm 2008-2011
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_langfile('geopage', 'plug');
require_once cot_incfile('geopage', 'plug', $cfg['plugin']['geopage']['engine']);
//ggoogle ABQIAAAAinKHrNUFpf3iUefgp2f11hRTwNsI1iETkL-_jwkYyGfBbXcMDxSfc025myUskOhyzWWIpawpSspQxQ
//

list($gx, $gy) = explode(' x ', $cfg['plugin']['geopage']['pagesize'], 2);
$GEOJS = '<div id="map_canvas" style="display:none;width: '.$gx.'; height: '.$gy.'"></div>';
cot_mappoint(htmlspecialchars($pag['page_title']), (float)$pag['page_geo_latitude'], (float)$pag['page_geo_longitude'], '', '');
cot_mapinicialize('map_canvas', $cfg['plugin']['geopage']['deflat'], $cfg['plugin']['geopage']['deflon'], $cfg['plugin']['geopage']['pointzoom'], true, $cfg['plugin']['geopage']['key']);

$t->assign('GEOMAP', $GEOJS);

?>