<?php


/**
 * [BEGIN_COT_EXT]
 * Code=geopage
 * Name=GeoPage
 * Description=Adds Yandex map piont for pages
 * Version=2.0.2
 * Date=2011-12-26
 * Author=esclkm
 * Copyright=(c) esclkm 2008-2011
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * [END_COT_EXT]
 * 
 * [BEGIN_COT_EXT_CONFIG]
 * engine=01:select:googlev3,googlev3_1:googlev3:Maps Engine
 * key=02:string:::Key
 * defzoom=03:string::1:Default zoom
 * deflat=04:string::0:Default latitude
 * deflon=05:string::0:Default longitude
 * pointzoom=06:string::14:Default one point view zoom
 * addeditsize=07:string::800px x 600px:Add/Edit map size
 * pagesize=08:string::800px x 600px:Page view map size
 * listsize=09:string::800px x 600px:List View map size
 * [END_COT_EXT_CONFIG]
 * 
 *  */
// * engine=01:select:yandex,cloudmade,google,googlev3,microsoft,multimap,ovi,openlayers,openspace,yahoo:yandex:Maps Engine
/**
 * plugin GeoPage for Cotonti Siena
 * 
 * @package geopage
 * @version 2.0.0
 * @author esclkm
 * @copyright (c) esclkm 2008-2011
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>