<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=page.list.tags
 * Tags=page.list.tpl:{GEOMAP}
 * [END_COT_EXT]
 */
 
/**
 * plugin GeoPage for Cotonti Siena
 * 
 * @package geopage
 * @version 2.5.0
 * @author esclkm
 * @copyright (c) esclkm 2008-2014
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_langfile('geopage', 'plug');
require_once cot_incfile('geopage', 'plug', $cfg['plugin']['geopage']['engine']);


list($gx, $gy) = explode(' x ', $cfg['plugin']['geopage']['listsize'], 2);
$GEOJS = '<div id="map_canvas" style="display:none;width: '.$gx.'; height: '.$gy.';"></div>';
$t->assign('GEOMAP', $GEOJS);

cot_mapinicialize('map_canvas', $cfg['plugin']['geopage']['deflat'], $cfg['plugin']['geopage']['deflon'], $cfg['plugin']['geopage']['defzoom'], true, $cfg['plugin']['geopage']['key']);
