<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=page.list.loop
 * Tags=page.list.tpl:{GEOMAP_ROW}
 * [END_COT_EXT]
 */
 
/**
 * plugin GeoPage for Cotonti Siena
 * 
 * @package geopage
 * @version 2.5.0
 * @author esclkm
 * @copyright (c) esclkm 2008-2014
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_langfile('geopage', 'plug');
require_once cot_incfile('geopage', 'plug', $cfg['plugin']['geopage']['engine']);

if((float)$pag['page_geo_latitude'] > 0 && (float)$pag['page_geo_longitude'] > 0)
{
	$pag['page_pageurl'] = empty($al) ? cot_url('page', array('c' => $pag['page_cat'], 'id' => $pag['page_id'])) : cot_url('page', array('c' => $pag['page_cat'], 'al' => $pag['page_alias']));
	
	cot_mappoint(htmlspecialchars($pag['page_title']), (float)$pag['page_geo_latitude'], (float)$pag['page_geo_longitude'], '<a href=\''.$pag['page_pageurl'].'\'>'.htmlspecialchars($pag['page_title']).'</a>', $pag['page_pageurl']);
}
