<?php

/**
 * plugin GeoPage for Cotonti Siena
 * 
 * @package geopage
 * @version 1.0.0
 * @author esclkm
 * @copyright (c) esclkm 2008-2011
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

function cot_mapinicialize($mapdivid, $lat, $lng, $zoom, $autocenter = true, $key='')
{
	global $cfg, $usr, $map_places;
	if ($autocenter)
	{
		//Центрируем и масштабируем карту
		$mapcenter = 'map.setCenter( latlngbounds.getCenter(), map.fitBounds(latlngbounds));';
	}
	cot_rc_link_footer("http://maps.google.com/maps/api/js?sensor=false");
	cot_rc_embed_footer('
		var map, markers = [], smarker;

		function initialize() {
			var infowindow = new google.maps.InfoWindow({
						content: ""
					});
			var latlng = new google.maps.LatLng('.$lat.', '.$lng.');
			var myOptions = {
				zoom: '.$zoom.',
				center: latlng,
				mapTypeId: google.maps.MapTypeId.ROADMAP
			};
			map = new google.maps.Map(document.getElementById("'.$mapdivid.'"),
				myOptions);

			setMarkers(map, places);
		}
		function setMarkers(map, locations) {
			//Определяем область показа маркеров
			if(locations.length)
			{
				var latlngbounds = new google.maps.LatLngBounds();	
				for (var i = 0; i < places.length; i++) {
					var myLatLng = new google.maps.LatLng(locations[i][1], locations[i][2]);
					//Добавляем координаты маркера в область
					latlngbounds.extend(myLatLng);
					var marker = new google.maps.Marker({
						position: myLatLng,
						map: map,   
						content: locations[i][3],
						link: locations[i][4],
						title: locations[i][0]
					}); 
					var infowindow = new google.maps.InfoWindow({
						content: locations[i][3]
					});
					markers.push(marker);
					if ( locations[i][3] != "")
					{
						google.maps.event.addListener(marker, "click", function() {
							infowindow.setContent(this.content);
							infowindow.open(map,this);
						});
					}

				}
				'.$mapcenter.'
			}
		};
		
		function setMarker(map, lat, lng, text) {
			//Определяем область показа маркеров
			var latlngbounds = new google.maps.LatLngBounds();	
			var myLatLng = new google.maps.LatLng(lat, lng);
			//Добавляем координаты маркера в область
			latlngbounds.extend(myLatLng);
			smarker = new google.maps.Marker({
				position: myLatLng,
				map: map,   
				title: text,
			}); 
			'.$mapcenter.'	 
		};
		
		function clearOverlays() {
			if (markers) {
				for (var i = 0; i < markers.length; i++) {
					markers[i].setMap(null);
				}
			}
		}
		var places = [];
		'.$map_places.'
		
		$(document).ready(function() { 
			$("#geolocate").show();
			$("#showonmap").show();
			$("#'.$mapdivid.'").show();
		  initialize();
		});
  ');
}

function cot_mappoint($text, $lat, $lng, $window ='', $href='')
{
	global $cfg, $usr, $map_places;
	static $map_pointnum;
	if (is_null($map_pointnum))
	{
		$map_pointnum = 0;
	}
	$map_places .='places['.$map_pointnum.'] = ["'.$text.'",'.$lat.','.$lng.', "'.$window.'", "'.$href.'"];
		';
	$map_pointnum++;
}
function cot_mapmarker($text, $lat, $lng)
{
	cot_rc_embed_footer
	('$(document).ready(function() { 
		  setMarker(map, '.$lat.', '.$lng.', "'.$text.'") 
		});');
}
function cot_mapgeolocate($showonmap_but, $geoloacate_but, $lat_sel, $lng_sel, $country, $region, $locality, $street, $title)
{
	cot_rc_embed_footer("
		var var_lat = $('".$lat_sel."');
		var var_lon = $('".$lng_sel."');
	
		var geocou = $('".$country."');
		var georeg = $('".$region."');
		var geoloc = $('".$locality."');
		var geostr = $('".$street."');
	
		var geotitle = $('".$title."'); 
		var geocoder = new google.maps.Geocoder();

		$(function() {
/*
			$('#address').autocomplete({
				//Определяем значение для адреса при геокодировании
				source: function(request, response) {
					geocoder.geocode( {
						'address': request.term
					}, function(results, status) {
						response($.map(results, function(item) {
							return {
								label:  item.formatted_address,
								value: item.formatted_address,
								latitude: item.geometry.location.lat(),
								longitude: item.geometry.location.lng()
							}
						}));
					})
				},
				//Выполняется при выборе конкретного адреса
				select: function(event, ui) {
					$('#latitude').val(ui.item.latitude);
					$('#longitude').val(ui.item.longitude);
					var location = new google.maps.LatLng(ui.item.latitude, ui.item.longitude);
					marker.setPosition(location);
					map.setCenter(location);
				}
			});
		});
*/
	$(document).ready(function() { 
			$('".$geoloacate_but."').click(function(){
				var address = geocou.val()+', '+georeg.val()+', '+geoloc.val()+', '+geostr.val();
				alert('OK');

			});
		});
		function calculateLatLng(address)
		{
			var lat='';
			var lng='';
			geocoder.geocode( {
				'address': address
			}, function(results, status) {
				if (status == google.maps.GeocoderStatus.OK)
				{
					window.document.getElementById('lat').value = results[0].geometry.location.lat();
					window.document.getElementById('lng').value = results[0].geometry.location.lng();
					alert('lat: '+results[0].geometry.location.lat()+'\nlng: '+results[0].geometry.location.lng()+'\ninputLat: '+window.document.getElementById('lat').value+'\ninputLng: '+window.document.getElementById('lng').value);
				}
			});
		}

		//Добавляем слушателя события обратного геокодирования для маркера при его перемещении  
		google.maps.event.addListener(smarker, 'drag', function() {
			geocoder.geocode({
				'latLng': this.getPosition()
			}, function(results, status) {
				if (status == google.maps.GeocoderStatus.OK) {
					if (results[0]) {
						$('#address').val(results[0].formatted_address);
						$('#latitude').val(marker.getPosition().lat());
						$('#longitude').val(marker.getPosition().lng());
					}
				}
			});
		});
");
}

?>