<?php

/**
 * plugin GeoPage for Cotonti Siena
 * 
 * @package geopage
 * @version 1.0.0
 * @author esclkm
 * @copyright (c) esclkm 2008-2011
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

function cot_mapinicialize($mapdivid, $lat, $lng, $zoom, $autocenter = true, $key='')
{
	global $cfg, $usr, $map_places;
	cot_rc_embed_footer('
		var zoom = '.$zoom.';
		var lat = '.$lat.';
		var lng = '.$lng.';
		var mapid = "'.$mapdivid.'";
		var places = [];
		'.$map_places.'
  ');
	cot_rc_link_footer("http://maps.google.com/maps/api/js??libraries=geometry&sensor=true");
	cot_rc_link_footer($cfg['plugins_dir'] . "/geopage/inc/geopage.googlev3.js");

}

function cot_mappoint($text, $lat, $lng, $window ='', $href='')
{
	global $cfg, $usr, $map_places;
	static $map_pointnum;
	if (is_null($map_pointnum))
	{
		$map_pointnum = 0;
	}
	$map_places .='places['.$map_pointnum.'] = ["'.$text.'",'.$lat.','.$lng.', "'.$window.'", "'.$href.'"];';
	$map_pointnum++;
}
function cot_mapmarker($text, $lat, $lng)
{
	cot_rc_embed_footer
	('$( window ).load(function() { 
		  setMarker(map, '.$lat.', '.$lng.', "'.$text.'") 
		});');
}

?>