<?php

/**
 * plugin GeoPage for Cotonti Siena
 * 
 * @package geopage
 * @version 1.0.0
 * @author esclkm
 * @copyright (c) esclkm 2008-2011
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

function cot_mapinicialize($mapdivid, $lat, $lng, $zoom, $autocenter = true, $key='')
{
	global $cfg, $usr, $map_places;
	if ($autocenter)
	{
		//Центрируем и масштабируем карту
		$mapcenter = '
			zoom = (markers.length > 1) ? map.fitBounds(latlngbounds) : zoom;
			map.setCenter( latlngbounds.getCenter(), zoom);';
	}
	cot_rc_link_footer("http://maps.google.com/maps/api/js?sensor=false");
	cot_rc_embed_footer('
		var map, markers = [], smarker;
		var zoom = '.$zoom.';
		function initialize() {
			var infowindow = new google.maps.InfoWindow({
						content: ""
					});
			var latlng = new google.maps.LatLng('.$lat.', '.$lng.');
			var myOptions = {
				zoom: '.$zoom.',
				center: latlng,
				mapTypeId: google.maps.MapTypeId.ROADMAP
			};
			map = new google.maps.Map(document.getElementById("'.$mapdivid.'"),
				myOptions);

			setMarkers(map, places);
		}
		function setMarkers(map, locations) {
			//Определяем область показа маркеров
			if(locations.length)
			{
				var latlngbounds = new google.maps.LatLngBounds();	
				for (var i = 0; i < places.length; i++) {
					var myLatLng = new google.maps.LatLng(locations[i][1], locations[i][2]);
					//Добавляем координаты маркера в область
					latlngbounds.extend(myLatLng);
					var marker = new google.maps.Marker({
						position: myLatLng,
						map: map,   
						content: locations[i][3],
						link: locations[i][4],
						title: locations[i][0]
					}); 
					var infowindow = new google.maps.InfoWindow({
						content: locations[i][3]
					});
					markers.push(marker);
					if ( locations[i][3] != "")
					{
						google.maps.event.addListener(marker, "click", function() {
							infowindow.setContent(this.content);
							infowindow.open(map,this);
						});
					}

				}
				'.$mapcenter.'
			}
		};
		
		function setMarker(map, lat, lng, text) {
			//Определяем область показа маркеров
			var latlngbounds = new google.maps.LatLngBounds();	
			var myLatLng = new google.maps.LatLng(lat, lng);
			//Добавляем координаты маркера в область
			if(smarker){smarker.setMap(null);}
			latlngbounds.extend(myLatLng);
			smarker = new google.maps.Marker({
				position: myLatLng,
				map: map,   
				title: text,
				draggable: true
			}); 
			'.$mapcenter.'	 
		};
		
		function clearOverlays() {
			if (markers) {
				for (var i = 0; i < markers.length; i++) {
					markers[i].setMap(null);
				}
			}
		}
		var places = [];
		'.$map_places.'
		
		$( window ).load(function() { 
			$("#geolocate").show();
			$("#showonmap").show();
			$("#'.$mapdivid.'").show();
		  initialize();
		});
  ');
}

function cot_mappoint($text, $lat, $lng, $window ='', $href='')
{
	global $cfg, $usr, $map_places;
	static $map_pointnum;
	if (is_null($map_pointnum))
	{
		$map_pointnum = 0;
	}
	$map_places .='places['.$map_pointnum.'] = ["'.$text.'",'.$lat.','.$lng.', "'.$window.'", "'.$href.'"];
		';
	$map_pointnum++;
}
function cot_mapmarker($text, $lat, $lng)
{
	cot_rc_embed_footer
	('$( window ).load(function() { 
		  setMarker(map, '.$lat.', '.$lng.', "'.$text.'") 
		});');
}
function cot_mapgeolocate($showonmap_but, $geoloacate_but, $lat_sel, $lng_sel, $country, $region, $locality, $street, $title)
{
	cot_rc_embed_footer("
		var var_lat = $('[name=rpagegeo_latitude]');
		var var_lon = $('[name=rpagegeo_longitude]');
	
		var geocou = $('[name=rpagegeo_country]');
		var georeg = $('[name=rpagegeo_region]');
		var geoloc = $('[name=rpagegeo_locality]');
		var geostr = $('[name=rpagegeo_street]');
	
		var geotitle = $('[name=rpagetitle]'); 
			
		

		$(window).load(function()  { 
			var geocoder = new google.maps.Geocoder();
			$('#geolocate').click(function(){
				var address = geocou.val()+', '+georeg.val()+', '+geoloc.val()+', '+geostr.val();
				
				geocoder.geocode( {'address': address}, function(results, status) {
					if (status == google.maps.GeocoderStatus.OK)
					{
						var_lat.val(results[0].geometry.location.lat());
						var_lon.val(results[0].geometry.location.lng());
						setMarker(map, var_lat.val(), var_lon.val(), geotitle.val());
					}
				}); 
			});
		
			$('#showonmap').click(function(){
				setMarker(map, var_lat.val(), var_lon.val(), geotitle.val());
			});
			
				//Добавляем слушателя события обратного геокодирования для маркера при его перемещении  
			google.maps.event.addListener(smarker, 'dragend', function() {
				geocoder.geocode({
					'latLng': this.getPosition()
				}, function(results, status) {
					if (status == google.maps.GeocoderStatus.OK) {
						if (results[0]) {
							var maptext = results[0].formatted_address;
							var maparr = maptext.split(/[,]/);
							geocou.val(maparr[2]);
							geoloc.val(maparr[1]);
							geostr.val(maparr[0]);
							var_lat.val(this.getPosition().lat());
							var_lon.val(this.getPosition().lng());
						}
					}
				});
			});
		});
	");
}

?>