<?php

/**
 * plugin GeoPage for Cotonti Siena
 * 
 * @package geopage
 * @version 1.0.0
 * @author esclkm
 * @copyright (c) esclkm 2008-2011
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

function cot_mapinicialize($mapdivid, $lat, $lng, $zoom, $autocenter = true, $key='')
{
	global $cfg, $usr, $map_places;
	cot_rc_embed_footer('
		var zoom = '.$zoom.';
		var lat = '.$lat.';
		var lng = '.$lng.';
		var mapid = "'.$mapdivid.'";
		var places = [];
		'.$map_places.'
  ');
	cot_rc_link_footer("http://maps.google.com/maps/api/js??libraries=geometry&sensor=true");
	cot_rc_link_footer($cfg['plugins_dir'] . "/geopage/js/geopage.googlev3.js");

}

function cot_mappoint($text, $lat, $lng, $window ='', $href='')
{
	global $cfg, $usr, $map_places;
	static $map_pointnum;
	if (is_null($map_pointnum))
	{
		$map_pointnum = 0;
	}
	$map_places .='places['.$map_pointnum.'] = ["'.$text.'",'.$lat.','.$lng.', "'.$window.'", "'.$href.'"];';
	$map_pointnum++;
}
function cot_mapmarker($text, $lat, $lng)
{
	cot_rc_embed_footer
	('$( window ).load(function() { 
		  setMarker(map, '.$lat.', '.$lng.', "'.$text.'") 
		});');
}

function cot_mapgetlatlng($country='', $region = '', $locality = '', $street = '')
{
	// http://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&sensor=true_or_false
	// Инициализируем курл
	
	//просп. Ленина, 51/1, Нижний Новгород, Нижегородская область
	//Каменецкий, Брест, Беларусь
	$adr = $street;
	$locality && $adr .= (!empty($adr) ? ', ' : '') . $locality;
	$region && $adr .= (!empty($adr) ? ', ' : '') . $region;
	$country && $adr .= (!empty($adr) ? ', ' : '') . $country;
	$adr = str_replace(' ', '+', $adr);
	
	if(empty($adr))
	{
		return false;
	}
	
	$ch = curl_init('http://maps.googleapis.com/maps/api/geocode/json?address='.$adr.'&sensor=true_or_false');

	// Параметры курла
	curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36');
	curl_setopt($ch, CURLOPT_HEADER, 0);
	// Следующая опция необходима для того, чтобы функция curl_exec() возвращала значение а не выводила содержимое переменной на экран
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);

	// Получаем html
	$result = curl_exec($ch);

	// Отключаемся
	curl_close($ch);
	
	json_decode($result, true);
	$lat = $result["results"]["geometry"]['location']['lat'];
	$lng = $result["results"]["geometry"]['location']['lng'];
	return array($lat, $lng);
}
