<?php
/**
 * plugin GeoPage for Cotonti Siena
 * 
 * @package geopage
 * @version 1.0.0
 * @author esclkm
 * @copyright (c) esclkm 2008-2011
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

$L['geolocate'] = 'Геолокация';
$L['ungeolocate'] = 'Обратная геолокация';
$L['showonmap'] = 'Показать на карте';

$L['page_title'] = 'Показать на карте';
$L['page_map_lat'] = 'Широта';
$L['page_map_lon'] = 'Долгота';
$L['page_map_country'] = 'Страна';
$L['page_map_region'] = 'Область';
$L['page_map_locality'] = 'Город';
$L['page_map_street'] = 'Адрес';
$L['geo_country'] = 'Страна';
$L['geo_region'] = 'Область';
$L['geo_locality'] = 'Город';
$L['geo_street'] = 'Адрес';
$L['geo_longitude'] = 'Долгота';
$L['geo_latitude'] = 'Широта';

?>